character_classes = {
    "Artificer",
    "Barbarian",
    "Bard",
    "Cleric",
    "Druid",
    "Fighter",
    "Monk",
    "Paladin",
    "Ranger",
    "Rogue",
    "Sorcerer",
    "Warlock",
    "Wizard",
}
professions = {
    "Skinner": "Can skin pelts of beasts, dragons, and monstrosities for armor and bonus gold",
    "Zoologist": "Can appropriately harvest and preserve monster organs for bonus gold",
    "Wayfinder": "May elect not to participate in travel encounters (once per excursion)",
    "Engineer": "Can build bridges, rafts, and gliders to navigate natural hazards",
    "Linguist": "Can speak, read, and translate mongrel tongues",
    "Physician": "Automatically stabilizes dying characters",
    "Cook": "Allows you to recover one hit die per short rest",
    "Surveyor": "Can create dungeon plans to turn in for gold that allows them to be upgraded to forts",
    "Dungeoneer": "Automatically disarm/trip found traps",
    "Survivalist": "Can build encampments that prevent night time attacks that disturb rest",
}
